FROM python:3.10-slim

ARG VERSION
ARG ARCHIVE_NAME
ARG ARCHIVE_SHA256

WORKDIR /app

ADD --checksum=sha256:${ARCHIVE_SHA256} \
    https://github.com/MrDave/StaticJinjaPlus/archive/${ARCHIVE_NAME} \
    /app/${ARCHIVE_NAME}

RUN tar -xzf ${ARCHIVE_NAME} && rm ${ARCHIVE_NAME}

WORKDIR /app/StaticJinjaPlus-${VERSION}

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "main.py"]